ci:
  skip: [pytest]

default_language_version:
  python: python3.12

repos:
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # ruff - linting + formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.1"
    hooks:
      - id: ruff
        name: ruff
      - id: ruff
        name: ruff-isort
        args: ["check", "--select", "I", "--fix"]

      - id: ruff-format
        name: ruff-format

  # mypy - lint-like type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy

  # bandit - find common security issues
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -r
          - src

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests --cov=src
        language: system
        types: [python]
        pass_filenames: false

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^uv.lock

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.8
    hooks:
      # Compile requirements
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
